Metrics/LineLength:
  Max: 150
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
