default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  username: postgres
  password:
  database: chatwoot_dev

test:
  <<: *default
  database: chatwoot_test

production:
  <<: *default
  database: chatwoot_production
  username: chatwoot_prod
  password: chatwoot_prod
